# Generated by Django 3.2.5 on 2021-11-07 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('province', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_relation', to='province.province')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'region_city',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('province', 'name')},
            },
        ),
    ]
